Controllers/SunglassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sunglasses_Assignment1_Ssoma.Data;
using Sunglasses_Assignment1_Ssoma.Models;

namespace Sunglasses_Assignment1_Ssoma.Controllers
{
    public class SunglassesController : Controller
    {
        private readonly MvcSunglassesContext _context;

        public SunglassesController(MvcSunglassesContext context)
        {
            _context = context;
        }

        // GET: Sunglasses
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sunglasses.ToListAsync());
        }

        // GET: Sunglasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sunglasses = await _context.Sunglasses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sunglasses == null)
            {
                return NotFound();
            }

            return View(sunglasses);
        }

        // GET: Sunglasses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sunglasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,ReleaseDate,ShadeType,Price,review,reviewScale,country")] Sunglasses sunglasses)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sunglasses);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sunglasses);
        }

        // GET: Sunglasses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sunglasses = await _context.Sunglasses.FindAsync(id);
            if (sunglasses == null)
            {
                return NotFound();
            }
            return View(sunglasses);
        }

        // POST: Sunglasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,ReleaseDate,ShadeType,Price,review,reviewScale,country")] Sunglasses sunglasses)
        {
            if (id != sunglasses.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sunglasses);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SunglassesExists(sunglasses.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sunglasses);
        }

        // GET: Sunglasses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sunglasses = await _context.Sunglasses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sunglasses == null)
            {
                return NotFound();
            }

            return View(sunglasses);
        }

        // POST: Sunglasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sunglasses = await _context.Sunglasses.FindAsync(id);
            _context.Sunglasses.Remove(sunglasses);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SunglassesExists(int id)
        {
            return _context.Sunglasses.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sunglasses_Assignment1_Ssoma</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <style>
        li{
            font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            font-weight:900;
            margin-right:10px;
            background-color:burlywood;
        }
        footer{
            font-family:Castellar;
            background-color:antiquewhite;
        }
        #heading{
            font-family:Bahnschrift;
            font-size:30px;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a id="heading" class="navbar-brand" asp-area="" asp-controller="Sunglasses" asp-action="Index">Sunglasses</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sunglasses" asp-action="Index">Product Catalogue</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now 2022 - Sunglasses_Assignment1_Ssoma - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>